
CONFIG_SERIAL=y
CONFIG_CONSOLE=y

CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y

####### custom for HIL_Simulator #######
CONFIG_APP_GPIO=y
CONFIG_APP_UART=n
CONFIG_APP_SPI=n
CONFIG_APP_ADC=n
CONFIG_APP_PWM=n

CONFIG_APP_USB_SERVICE=y

# Modern USBD Stack Configuration Flags (Replaces USB_DEVICE_STACK)
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y